spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      lettuce:
        pool:
          min-idle: 8
          max-idle: 16
          max-active: 32
      database: 0
      timeout: 3000ms
      password: nP1jX7iU
      sentinel:
        master: WebSession
        nodes: 10.74.82.52:26379,10.74.82.53:26379,10.74.82.54:26379
        password: nP1jX7iU
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
tlq:
  name-srv-url: tcp://10.74.82.52:9888
  domain: umdc