// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

// Protobuf Java Version: 4.26.1
package com.example.sample;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.sample.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
