// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

// Protobuf Java Version: 4.26.1
package com.example.sample;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.sample.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.example.sample.ReqBody data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.com.example.sample.ReqBody data = 3;</code>
   * @return The data.
   */
  com.example.sample.ReqBody getData();
  /**
   * <code>.com.example.sample.ReqBody data = 3;</code>
   */
  com.example.sample.ReqBodyOrBuilder getDataOrBuilder();
}
