// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

// Protobuf Java Version: 4.26.1
package com.example.sample;

public interface ReqBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.sample.ReqBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 num = 2;</code>
   * @return The num.
   */
  int getNum();
}
