// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto
// Protobuf Java Version: 4.26.1

package com.example.sample;

public final class Sample {
  private Sample() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Sample.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_sample_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_sample_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_sample_ReqBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_sample_ReqBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_sample_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_example_sample_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\022\022com.example.sample\"X\n\014He" +
      "lloRequest\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(" +
      "\t\022)\n\004data\030\003 \001(\0132\033.com.example.sample.Req" +
      "Body\"$\n\007ReqBody\022\014\n\004name\030\001 \001(\t\022\013\n\003num\030\002 \001" +
      "(\005\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\tB\036\n\022com" +
      ".example.sampleB\006SampleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_example_sample_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_sample_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_sample_HelloRequest_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
    internal_static_com_example_sample_ReqBody_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_example_sample_ReqBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_sample_ReqBody_descriptor,
        new java.lang.String[] { "Name", "Num", });
    internal_static_com_example_sample_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_example_sample_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_example_sample_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
